feature:
  # -- Enable / Disable the installation of Kyverno
  kyverno: true
  # -- Enable / Disable the installation of Kyverno FinOps Policies
  finops-policies: true
  # -- Enable / Disable the installation of the VPA Controller
  vpa: false
  # -- Enable / Disable the installation of the Grafana
  grafana: true
  # -- Enable / Disable the installation of Grafana FinOps Dashboards
  finops-dashboards: true
  # -- Enable / Disable the installation of OpenCost
  opencost: true
  # -- Enable / Disable the installation of OpenCost Exporter
  opencost-exporter: true

# @ignored
vpa:
  updater:
    resources:
      {
        "limits": { "cpu": "100m", "memory": "500Mi" },
        "requests": { "cpu": "100m", "memory": "500Mi" },
      }
  recommender:
    resources:
      {
        "limits": { "cpu": "100m", "memory": "500Mi" },
        "requests": { "cpu": "100m", "memory": "500Mi" },
      }
    extraArgs:
      prometheus-address: http://frontend.prometheus-system.svc.cluster.local:9090
      storage: prometheus
  admissionController:
    enabled: false

# @ignore
kyverno:
  reportsController:
    rbac:
      clusterRole:
        extraResources:
          - apiGroups: [events.k8s.io]
            resources: ["events"]
            verbs: [create]
  grafana:
    enabled: true
    labels:
      grafana_dashboard: "finops"

# @ignored
grafana:
  rbac:
    namespaced: true
  testFramework:
    enabled: false

  adminUser: finops
  adminPassword: s7@ck # pragma: allowlist secret
  enableServiceLinks: false
  plugins: []
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://kubecost-prometheus-server.kubecost.svc.cluster.local
          access: proxy
          isDefault: true

  grafana.ini:
    analytics:
      check_for_updates: false
  sidecar:
    dashboards:
      enabled: true
      labelValue: finops

# @ignored
prometheus-opencost-exporter:
  podSecurityContext:
    fsGroup: 2000
  opencost:
    prometheus:
      amp: {}
      thanos: {}
