apiVersion: kyverno.io/v2
kind: ClusterCleanupPolicy
metadata:
  name: cleandeploy
  annotations:
    policies.kyverno.io/title: Cluster Cleanup Policy
    policies.kyverno.io/category: FinOps
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Service
    policies.kyverno.io/minversion: 1.9.0
    policies.kyverno.io/description: >-
      Automate the resource cleanup process by using a CleanupPolicy.

      Remove Deployments which have the label canremove: "true" if they have less than two replicas on a schedule of every 5 minutes.
  labels:
    {{- include "finops-policies.labels" . | nindent 4 }}
spec:
  match:
    any:
    - resources:
        kinds:
          - Deployment
        selector:
          matchLabels:
            canremove: "true"
  conditions:
    any:
    - key: "{{`{{ target.spec.replicas }}`}}"
      operator: LessThan
      value: 2
  schedule: "*/5 * * * *"
