{{- if and .Values.opencost.customPricing.createConfigmap .Values.opencost.customPricing.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.opencost.customPricing.configmapName }}
data:
  {{ .Values.opencost.configFileName }}.json: |-
    {
{{- range $key, $val := .Values.opencost.customPricing.costModel }}
{{ $key | quote | indent 6}}: {{ $val | quote }},
{{- end}}
      "provider" : {{ .Values.opencost.provider | quote }}
    }
{{- end }}