{{ if and .Values.gke .Values.gke.podmonitoring }}
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: opencost-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-opencost-exporter
  endpoints:
  - port: http
    interval: 60s
    metricRelabeling:
    - sourceLabels: [exported_namespace]
      targetLabel: "orig_namespace"
    - sourceLabels: [exported_instance]
      targetLabel: "orig_instance"
  targetLabels:
    metadata: []
{{end}}
