{
 "title": "FinOps Stack: Used | Wasted Resources for cluster & namespace",
 "description": "Dashboard to show the resource requests vs allocatable in the cluster and selected namespace",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels,exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster wide resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable{resource=\"memory\"} / 1024 ) by (exported_instance))",
     "legendFormat": "Allocatable Memory"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{resource=\"memory\"} / 1024 ) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)\n )",
     "legendFormat": "Requested Memory"
    },
    {
     "expr": "min(sum(kube_node_status_capacity_memory_bytes / 1024 ) by (exported_instance))",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum(kube_metrics_server_pods_mem)",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "timeseries",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(sum(kube_node_status_allocatable_cpu_cores) by (exported_instance))",
     "legendFormat": "Allocatable CPU Cores"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (pod) == 1)\n )",
     "legendFormat": "Requested CPU cores"
    },
    {
     "expr": "sum(rate(kubernetes_io:container_cpu_core_usage_time{monitored_resource=\"k8s_container\"}[1m]))",
     "legendFormat": "Used CPU cores"
    }
   ]
  },
  {
   "title": "Wasted Memory by Namespace %",
   "type": "bargauge",
   "description": "NOTE: fixed at the last 60mins as this is an expensive query",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "((100 * \n(sum(label_replace(kubernetes_io:container_memory_used_bytes, \"exported_namespace\", \"$1\", \"namespace_name\", \"(.+)\")) by (exported_namespace))\n/ \nsum(sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (exported_namespace, pod)) by (exported_namespace)\n- 100) * -1) > 0",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Requests/Limit/Usage by Namespace",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{exported_namespace=~\".*\", resource=\"memory\"}) by (exported_namespace, pod)\n * on (exported_namespace, pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", exported_namespace=~\".*\"}) by (exported_namespace, pod) == 1)\n ) by (exported_namespace)",
     "legendFormat": "Requested Memory"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_limits{exported_namespace=~\".*\", resource=\"memory\"}) by (exported_namespace, pod)\n * on (exported_namespace, pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", exported_namespace=~\".*\"}) by (exported_namespace, pod) == 1)\n ) by (exported_namespace)",
     "legendFormat": "Limit Memory"
    },
    {
     "expr": "sum(label_replace(kubernetes_io:container_memory_used_bytes, \"exported_namespace\", \"$1\", \"namespace_name\", \"(.+)\")) by (exported_namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (exported_namespace, pod)* on (exported_namespace, pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (exported_namespace, pod) == 1)) by (exported_namespace))\n-\n(sum(label_replace(kubernetes_io:container_memory_used_bytes, \"exported_namespace\", \"$1\", \"namespace_name\", \"(.+)\")) by (exported_namespace))",
     "legendFormat": "Wasted Memory"
    },
    {
     "expr": "((100 * \n(sum(label_replace(kubernetes_io:container_memory_used_bytes, \"exported_namespace\", \"$1\", \"namespace_name\", \"(.+)\")) by (exported_namespace))\n/ \nsum(sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (exported_namespace, pod)* on (exported_namespace, pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (exported_namespace, pod) == 1)) by (exported_namespace)\n- 100) * -1)",
     "legendFormat": "Wasted Memory %"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{exported_namespace=~\".*\", resource=\"cpu\"}) by (exported_namespace, pod)\n * on (exported_namespace, pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", exported_namespace=~\".*\"}) by (exported_namespace, pod) == 1)\n ) by (exported_namespace)",
     "legendFormat": "Requested CPU"
    },
    {
     "expr": "sum(\nsum(kube_pod_container_resource_limits{exported_namespace=~\".*\", resource=\"cpu\"}) by (exported_namespace, pod)\n * on (exported_namespace, pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (exported_namespace, pod) == 1)\n ) by (exported_namespace)",
     "legendFormat": "Limit CPU"
    },
    {
     "expr": "sum(label_replace(rate(kubernetes_io:container_cpu_core_usage_time{monitored_resource=\"k8s_container\"}[1m]), \"exported_namespace\", \"$1\", \"namespace_name\", \"(.+)\")) by (exported_namespace)",
     "legendFormat": "Used CPU"
    },
    {
     "expr": "(sum(sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (exported_namespace, pod)* on (exported_namespace, pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (exported_namespace, pod) == 1)) by (exported_namespace))\n-\nsum(label_replace(rate(kubernetes_io:container_cpu_core_usage_time{monitored_resource=\"k8s_container\"}[1m]), \"exported_namespace\", \"$1\", \"namespace_name\", \"(.+)\")) by (exported_namespace)",
     "legendFormat": "Wasted CPU"
    },
    {
     "expr": "((100 * \n(sum(label_replace(rate(kubernetes_io:container_cpu_core_usage_time{monitored_resource=\"k8s_container\"}[1m]), \"exported_namespace\", \"$1\", \"namespace_name\", \"(.+)\")) by (exported_namespace))\n/ \nsum(sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (exported_namespace, pod)* on (exported_namespace, pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\"}) by (exported_namespace, pod) == 1)) by (exported_namespace)\n- 100) * -1)",
     "legendFormat": "Wasted CPU %"
    }
   ]
  },
  {
   "title": "Resource usage by namespace: ${namespace}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Shows requested memory vs used memory for the specified namespace",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{exported_namespace=\"$namespace\", resource=\"memory\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", exported_namespace=\"$namespace\"}) by (pod) == 1)\n ) / 1000",
     "legendFormat": "Requested Memory"
    },
    {
     "expr": "sum(rate(kubernetes_io:container_cpu_core_usage_time{monitored_resource=\"k8s_container\", namespace_name=\"$namespace\"}[1m]))*1048576",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "timeseries",
   "description": "Shows requested CPU vs used CPU for the specified namespace",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\nsum(kube_pod_container_resource_requests{exported_namespace=\"$namespace\", resource=\"cpu\"}) by (pod)\n * on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\", exported_namespace=\"$namespace\"}) by (pod) == 1)\n )",
     "legendFormat": "Requested CPU"
    },
    {
     "expr": "sum(rate(kubernetes_io:container_cpu_core_usage_time{monitored_resource=\"k8s_container\", namespace_name=\"$namespace\"}[1m])) ",
     "legendFormat": "Used CPU"
    }
   ]
  },
  {
   "title": "Memory Request/Limit/Usage by Pod",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{exported_namespace=\"$namespace\", resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{exported_namespace=\"$namespace\", resource=\"memory\"})  by (pod)"
    },
    {
     "expr": "sum(label_replace(kubernetes_io:container_memory_used_bytes{namespace_name=\"$namespace\"}, \"pod\", \"$1\", \"pod_name\", \"(.+)\") / 1024) by (pod)"
    },
    {
     "expr": "((100 * \n(sum(label_replace(kubernetes_io:container_memory_used_bytes{namespace_name=\"$namespace\"}, \"pod\", \"$1\", \"pod_name\", \"(.+)\")) by (pod))\n/ \nsum(sum(kube_pod_container_resource_requests{resource=\"memory\", exported_namespace=~\"$namespace\"}) by (pod)* on (pod) group_left()  (sum(kube_pod_status_phase{exported_namespace=\"$namespace\",phase=\"Running\"}) by (pod) == 1)) by (pod)\n- 100) * -1)",
     "legendFormat": "Wasted Live %"
    }
   ]
  },
  {
   "title": "CPU Request/Limit by Pod",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{exported_namespace=\"$namespace\", resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{exported_namespace=\"$namespace\", resource=\"cpu\"})  by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(label_replace(rate(kubernetes_io:container_cpu_core_usage_time{monitored_resource=\"k8s_container\",namespace_name=\"$namespace\"}[1m]), \"pod\", \"$1\", \"pod_name\", \"(.+)\")) by (pod)"
    },
    {
     "expr": "((100 * \n(sum(label_replace(rate(kubernetes_io:container_cpu_core_usage_time{monitored_resource=\"k8s_container\",namespace_name=\"$namespace\"}[1m]), \"pod\", \"$1\", \"pod_name\", \"(.+)\")) by (pod))\n/ \nsum(sum(kube_pod_container_resource_requests{resource=\"cpu\",exported_namespace=\"$namespace\"}) by (pod)* on (pod) group_left()  (sum(kube_pod_status_phase{phase=\"Running\",exported_namespace=\"$namespace\"}) by (pod) == 1)) by( pod)\n- 100) * -1)",
     "legendFormat": "Wasted CPU %"
    }
   ]
  },
  {
   "title": "Memory usage by Pod over time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum(label_replace(kubernetes_io:container_memory_used_bytes{namespace_name=\"$namespace\"}, \"pod\", \"$1\", \"pod_name\", \"(.+)\") / 1024) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage by Pod over time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum(label_replace(rate(kubernetes_io:container_cpu_core_usage_time{monitored_resource=\"k8s_container\",namespace_name=\"$namespace\"}[1m]), \"pod\", \"$1\", \"pod_name\", \"(.+)\")) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}