{
 "title": "Multi-day summary",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "time_period_days", "label": "Time period (days)", "query": "1,7,30" }
  ]
 },
 "panels": [
  {
   "title": "Estimated cluster cost",
   "type": "stat",
   "description": "Based on the average total hourly node cost",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg by (exported_instance) (node_total_hourly_cost)) * 24 * ${time_period_days}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Hour Cost",
   "type": "timeseries",
   "description": "Based on total node price",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "sum(node_total_hourly_cost)", "legendFormat": "Cluster Hour Cost" }
   ]
  },
  {
   "title": "Top 20 namespaces by estimated cost",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(20,\n  sum(\n    sum(container_memory_allocation_bytes) \n    by (exported_namespace,exported_instance)\n    * on(exported_instance) group_left() (\n\t\t\tnode_ram_hourly_cost{} / 1024 / 1024 / 1024 * (24 * ${time_period_days})\n\t\t)\n\n    +\n\n    sum(container_cpu_allocation) \n    by (exported_namespace,exported_instance)\n    * on(exported_instance) group_left() (\n\t\t\tnode_cpu_hourly_cost{} * (24 * ${time_period_days})\n\t\t)\n  ) by (exported_namespace)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 20 workloads by estimated cost",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(20,sum by (exported_namespace,owner_name)(((sum(container_memory_allocation_bytes) \n\tby (instance,exported_instance,exported_namespace,pod)\n\t+ on (instance,exported_namespace,pod) group_left(owner_name) kube_pod_owner{} * 0)\n\t* on(exported_instance) group_left() (\n\t\tnode_ram_hourly_cost{instance_type != \"\", job =\"opencost-exporter\"} / 1024 / 1024 / 1024 * (24 * ${time_period_days})\n  \t))\n\t+\n\t((sum(container_cpu_allocation) \n\tby (instance,exported_instance,exported_namespace,pod)\n\t+ on (instance,exported_namespace,pod) group_left(owner_name) kube_pod_owner{} * 0)\n\t* on(exported_instance) group_left() (\n\t\tnode_cpu_hourly_cost{instance_type != \"\", job =\"opencost-exporter\"} * (24 * ${time_period_days})\n  \t))\n\t))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 20 containers by estimated cost",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(20,\n\t\tsum(\n\t\t  sum(container_memory_allocation_bytes) by (instance,exported_namespace,exported_instance, container)\n\t\t  * on(exported_instance) group_left() (\n\t\t\t\t  node_ram_hourly_cost{instance_type != \"\", job =\"opencost-exporter\", orig_namespace = \"\"} / 1024 / 1024 / 1024 * (24 * ${time_period_days})\n\t\t\t  )\n\t\t  +\n\t\t  sum(container_cpu_allocation) by (instance,exported_namespace,exported_instance, container)\n\t\t  * on(exported_instance) group_left() (\n\t\t\t\t  node_cpu_hourly_cost{instance_type != \"\", job =\"opencost-exporter\", orig_namespace = \"\"} * (24 * ${time_period_days})\n\t\t\t  )\n\t\t) by (exported_namespace, container)\n\t  )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory efficiency (%) by Namespace",
   "type": "bargauge",
   "description": "NOTE: only namespaces with < 80% efficiency shown",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (namespace_name)(avg_over_time(kubernetes_io:container_memory_used_bytes[5m])) / sum by (namespace_name)(avg_over_time(kubernetes_io:container_memory_request_bytes[5m])) * 100) < 79",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU efficiency (%) by Namespace",
   "type": "bargauge",
   "description": "NOTE: only namespaces with < 80% efficiency shown",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum by (namespace_name)(rate(kubernetes_io:container_cpu_core_usage_time{monitored_resource=\"k8s_container\"}[${__interval}])) / sum by (namespace_name)(avg_over_time(kubernetes_io:container_cpu_request_cores{monitored_resource=\"k8s_container\"}[${__interval}]))) * 100) < 80",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}