{
 "title": "OpenCost Dashboard-new",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster wide", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Daily Cloud Costs",
   "type": "stat",
   "description": "Based on the average node_total_hourly_cost in the last 30d",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg by (instance) (node_total_hourly_cost)) * 24",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Hour Cost",
   "type": "timeseries",
   "description": "Based on total node price",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "sum(node_total_hourly_cost)", "legendFormat": "Cluster Hour Cost" }
   ]
  },
  {
   "title": "Estimative Monthly Cloud Costs",
   "type": "stat",
   "description": "Based on the average total hourly node cost from the last 30d",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg by (instance) (node_total_hourly_cost)) * 24 * 30",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relative price now vs (7/1)d ago (Hour Price)",
   "type": "timeseries",
   "description": "Based on total node price over 7d and 1d",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n  avg_over_time(\n    sum(node_total_hourly_cost) [1d:1h]\n  )\n/\n  avg_over_time(\n    sum(node_total_hourly_cost) [7d:1h]\n  )\n)",
     "legendFormat": "Relative price now vs 7d ago (Hour Price)"
    },
    {
     "expr": "1 - (\n  avg(sum(node_total_hourly_cost))\n/\n  avg_over_time(\n    sum(node_total_hourly_cost) [1d:1h]\n  )\n)",
     "legendFormat": "Relative price now vs 1d ago (Hour Price)"
    }
   ]
  },
  {
   "title": "Standard Variation of Cost by InstanceType (7d/1d)",
   "type": "timeseries",
   "description": "Based on total node price over 7d and 1d",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "stdvar_over_time( sum(node_total_hourly_cost) by (instance_type) [7d:1d] )",
     "legendFormat": "Relative price now vs 7d ago (Hour Price)"
    }
   ]
  },
  {
   "title": "Estimated Top 20 Namespaces",
   "type": "table",
   "gridPos": { "h": 22, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(20,\n  sum(\n    sum(container_memory_allocation_bytes) \n    by (namespace,instance)\n    * on(instance) group_left() (\n\t\t\tnode_ram_hourly_cost{} / 1024 / 1024 / 1024 * 720\n\t\t\t+ on(node,instance_type) group_left()\n\t\t\tlabel_replace\n\t\t\t(\n\t\t\t\tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t\t) * 0\n\t\t)\n\n    +\n\n    sum(container_cpu_allocation) \n    by (namespace,instance)\n    * on(instance) group_left() (\n\t\t\tnode_cpu_hourly_cost{} * 720\n\t\t\t+ on(node,instance_type) group_left()\n\t\t\tlabel_replace\n\t\t\t(\n\t\t\t\tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t\t) * 0\n\t\t)\n  ) by (namespace)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated Top 20 Containers",
   "type": "table",
   "gridPos": { "h": 22, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(20,\n  sum(\n    sum(container_memory_allocation_bytes) by (namespace,instance, container)\n    * on(instance) group_left() (\n\t\t\tnode_ram_hourly_cost{} / 1024 / 1024 / 1024 * 720\n\t\t\t+ on(node,instance_type) group_left()\n\t\t\tlabel_replace\n\t\t\t(\n\t\t\t\tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t\t) * 0\n\t\t)\n    +\n    sum(container_cpu_allocation) by (namespace,instance, container)\n    * on(instance) group_left() (\n\t\t\tnode_cpu_hourly_cost{} * 720\n\t\t\t+ on(node,instance_type) group_left()\n\t\t\tlabel_replace\n\t\t\t(\n\t\t\t\tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t\t) * 0\n\t\t)\n  ) by (namespace, container)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated Top 20 Pods",
   "type": "table",
   "gridPos": { "h": 22, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(20,\n  sum(\n    sum(container_memory_allocation_bytes) by (namespace,instance, pod)\n    * on(instance) group_left() (\n\t\t\tnode_ram_hourly_cost{} / 1024 / 1024 / 1024 * 720\n\t\t\t+ on(node,instance_type) group_left()\n\t\t\tlabel_replace\n\t\t\t(\n\t\t\t\tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t\t) * 0\n\t\t)\n    +\n    sum(container_cpu_allocation) by (namespace,instance, pod)\n    * on(instance) group_left() (\n\t\t\tnode_cpu_hourly_cost{} * 720\n\t\t\t+ on(node,instance_type) group_left()\n\t\t\tlabel_replace\n\t\t\t(\n\t\t\t\tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t\t) * 0\n\t\t)\n  ) by (pod)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hour Cost by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(sum(container_memory_allocation_bytes) by (namespace,instance) * on(instance) group_left() (\n\t\t\t\tnode_ram_hourly_cost{} / 1024 / 1024 / 1024\n\t\t\t\t+ on(node,instance_type) group_left()\n\t\t\t\t\tlabel_replace\n\t\t\t\t\t(\n\t\t\t\t\t\tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t\t\t\t) * 0\n\t\t\t)\n  + \n  sum(container_cpu_allocation) by (namespace,instance) * on(instance) group_left() (\n\t  \t\t\tnode_cpu_hourly_cost{} + on(node,instance_type) group_left()\n\t\t  \t\t\tlabel_replace\n\t\t  \t\t\t(\n\t\t  \t\t\t\tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t  \t\t\t) * 0\n\t\t  \t)) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Hour Cost by Container",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(sum(container_memory_allocation_bytes) by (container,namespace, instance) * on(instance) group_left() (\n\t\t\t\tnode_ram_hourly_cost{} / 1024 / 1024 / 1024\n\t\t\t\t+ on(node,instance_type) group_left()\n\t\t\t\t\tlabel_replace\n\t\t\t\t\t(\n\t\t\t\t\t\tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t\t\t\t) * 0\n\t\t\t)\n  + \n  sum(container_cpu_allocation) by (container,namespace, instance) * on(instance) group_left() (\n\t  \t\t\tnode_cpu_hourly_cost{} + on(node,instance_type) group_left()\n\t\t  \t\t\tlabel_replace\n\t\t  \t\t\t(\n\t\t  \t\t\t\tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t  \t\t\t) * 0\n\t\t  \t)) by (namespace, container)",
     "legendFormat": "{{namespace}} / {{container}}"
    }
   ]
  },
  { "title": "By Namespace $namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Estimated Top 20 Containers",
   "type": "table",
   "gridPos": { "h": 21, "w": 5, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(20,\n  sum(\n    sum(container_memory_allocation_bytes{namespace=~\"$namespace\"}) by (instance, container)\n    * on(instance) group_left() (\n\t\t\tnode_ram_hourly_cost / 1024 / 1024 / 1024 * 720\n\t\t\t+ on(node,instance_type) group_left()\n\t\t\tlabel_replace\n\t\t\t(\n\t\t\t\tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t\t) * 0\n\t\t)\n    +\n    sum(container_cpu_allocation{namespace=~\"$namespace\"}) by (instance, container)\n    * on(instance) group_left() (\n\t\t\tnode_cpu_hourly_cost{} * 720\n\t\t\t+ on(node,instance_type) group_left()\n\t\t\tlabel_replace\n\t\t\t(\n\t\t\t\tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t\t) * 0\n\t\t)\n  ) by (container)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated monthly costs",
   "type": "stat",
   "description": "Based on current usage",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum(container_memory_allocation_bytes{namespace=~\"$namespace\"}) by (instance)\n  * on(instance) group_left() (\n    node_ram_hourly_cost / 1024 / 1024 / 1024\n    + on(node,instance_type) group_left()\n    label_replace\n    (\n      kube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n    ) * 0\n  )\n  +\n  sum(container_cpu_allocation{namespace=~\"$namespace\"}) by (instance)\n  * on(instance) group_left() (\n    node_cpu_hourly_cost{}\n    + on(node,instance_type) group_left()\n    label_replace\n    (\n      kube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n    ) * 0\n  ) \n) * 720",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated monthly costs",
   "type": "timeseries",
   "description": "Based on current usage",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 60 },
   "targets": [
    {
     "expr": "sum(\n  sum(container_memory_allocation_bytes{namespace=~\"$namespace\"}) by (instance)\n  * on(instance) group_left() (\n    node_ram_hourly_cost / 1024 / 1024 / 1024\n    + on(node,instance_type) group_left()\n    label_replace\n    (\n      kube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n    ) * 0\n  )\n  +\n  sum(container_cpu_allocation{namespace=~\"$namespace\"}) by (instance)\n  * on(instance) group_left() (\n    node_cpu_hourly_cost{}\n    + on(node,instance_type) group_left()\n    label_replace\n    (\n      kube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n    ) * 0\n  ) \n) * 720",
     "legendFormat": "Costs"
    }
   ]
  },
  {
   "title": "Estimated Daily Costs",
   "type": "stat",
   "description": "Based on current usage",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum(container_memory_allocation_bytes{namespace=~\"$namespace\"}) by (instance)\n  * on(instance) group_left() (\n    node_ram_hourly_cost / 1024 / 1024 / 1024\n    + on(node,instance_type) group_left()\n    label_replace\n    (\n      kube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n    ) * 0\n  )\n  +\n  sum(container_cpu_allocation{namespace=~\"$namespace\"}) by (instance)\n  * on(instance) group_left() (\n    node_cpu_hourly_cost{}\n    + on(node,instance_type) group_left()\n    label_replace\n    (\n      kube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n    ) * 0\n  ) \n) * 24",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated Daily Costs",
   "type": "timeseries",
   "description": "Based on current usage",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 67 },
   "targets": [
    {
     "expr": "sum(\n  sum(container_memory_allocation_bytes{namespace=~\"$namespace\"}) by (instance)\n  * on(instance) group_left() (\n    node_ram_hourly_cost / 1024 / 1024 / 1024\n    + on(node,instance_type) group_left()\n    label_replace\n    (\n      kube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n    ) * 0\n  )\n  +\n  sum(container_cpu_allocation{namespace=~\"$namespace\"}) by (instance)\n  * on(instance) group_left() (\n    node_cpu_hourly_cost{}\n    + on(node,instance_type) group_left()\n    label_replace\n    (\n      kube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n    ) * 0\n  ) \n) * 24",
     "legendFormat": "Costs"
    }
   ]
  },
  {
   "title": "Estimated Hourly Costs",
   "type": "stat",
   "description": "Based on current usage",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum(container_memory_allocation_bytes{namespace=~\"$namespace\"}) by (instance)\n  * on(instance) group_left() (\n    node_ram_hourly_cost / 1024 / 1024 / 1024\n    + on(node,instance_type) group_left()\n    label_replace\n    (\n      kube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n    ) * 0\n  )\n  +\n  sum(container_cpu_allocation{namespace=~\"$namespace\"}) by (instance)\n  * on(instance) group_left() (\n    node_cpu_hourly_cost{}\n    + on(node,instance_type) group_left()\n    label_replace\n    (\n      kube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n    ) * 0\n  ) \n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated Hourly Costs",
   "type": "timeseries",
   "description": "Based on current usage",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 74 },
   "targets": [
    {
     "expr": "sum(\n  sum(container_memory_allocation_bytes{namespace=~\"$namespace\"}) by (instance)\n  * on(instance) group_left() (\n    node_ram_hourly_cost / 1024 / 1024 / 1024\n    + on(node,instance_type) group_left()\n    label_replace\n    (\n      kube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n    ) * 0\n  )\n  +\n  sum(container_cpu_allocation{namespace=~\"$namespace\"}) by (instance)\n  * on(instance) group_left() (\n    node_cpu_hourly_cost{}\n    + on(node,instance_type) group_left()\n    label_replace\n    (\n      kube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n    ) * 0\n  ) \n)",
     "legendFormat": "Costs"
    }
   ]
  },
  {
   "title": "Hour Price by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(20,\n  sum(\n    sum(container_memory_allocation_bytes{namespace=~\"$namespace\"}) by (instance, container)\n    * on(instance) group_left() (\n\t\t\tnode_ram_hourly_cost / 1024 / 1024 / 1024 * 720\n\t\t\t+ on(node,instance_type) group_left()\n\t\t\tlabel_replace\n\t\t\t(\n\t\t\t\tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t\t) * 0\n\t\t)\n    +\n    sum(container_cpu_allocation{namespace=~\"$namespace\"}) by (instance, container)\n    * on(instance) group_left() (\n\t\t\tnode_cpu_hourly_cost{} * 720\n\t\t\t+ on(node,instance_type) group_left()\n\t\t\tlabel_replace\n\t\t\t(\n\t\t\t\tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t\t) * 0\n\t\t)\n  ) by (container)\n)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}