{{ if and .Values.gke .Values.gke.podmonitoring .Values.feature.opencost }}
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: opencost
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: opencost
  endpoints:
  - port: http
    interval: 60s
  targetLabels:
    metadata: []
{{end}}
