service:
  enabled: false
opencost:
  prometheus:
    external:
      enabled: true
      url: http://gmp-proxy
    internal:
      enabled: false
  exporter:
    cloudProviderApiKey: "dummy_key"
    # Persistent volume claim for storing the data. eg: csv file
    persistence:
      enabled: false
      # -- Annotations for persistent volume
      annotations: {}
      # -- Access mode for persistent volume
      accessMode: ""
      # -- Storage class for persistent volume
      storageClass: "standard-rwo"
      # -- Size for persistent volume
      size: "10g"