  rbac:
    namespaced: true
  testFramework:
    enabled: false

  adminUser: finops
  adminPassword: admin123 # pragma: allowlist secret
  enableServiceLinks: false
  plugins: []

  grafana.ini:
    analytics:
      check_for_updates: false
  sidecar:
    dashboards:
      enabled: true
      labelValue: finops