podSecurityContext:
  fsGroup: 2000

opencost:
  customPricing:
    enabled: true
  exporter:
    resources:
      requests:
        cpu: 50m
        memory: 175M
      limits:
        cpu: 50m
        memory: 256M
