repositories:
- name: kyverno
  url: https://kyverno.github.io/kyverno/
- name: opencost
  url: https://opencost.github.io/opencost-helm-chart
- name: prometheus-opencost-exporter
  url: https://prometheus-community.github.io/helm-charts
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: vpa
  url: https://charts.fairwinds.com/stable
- name: cert-manager
  url: https://charts.jetstack.io

---
helmDefaults:
  wait: true
---
environments:
  default:
    values:
    - ./config/common/enabled.yaml
---
releases:
- name: kyverno
  version: "3.2.6"
  chart: kyverno/kyverno
  condition: kyverno.enabled
  namespace: finops-stack
  values:
  - "./config/common/kyverno-values.yaml"
  - "./config/{{ requiredEnv "HOST_ENV" }}/kyverno-values.yaml"  

- name: finops-policies
  version: "0.0.6"
  chart: "cert-manager/finops-policies"
  condition: finops-policies.enabled
  namespace: finops-stack
  disableValidationOnInstall: true
  needs:
  - kyverno
  

- name: grafana
  version: "8.4.7"
  chart: grafana/grafana
  condition: grafana.enabled
  namespace: finops-stack
  values:
  - "./config/common/grafana-values.yaml"
  - "./config/{{ requiredEnv "HOST_ENV" }}/grafana-values.yaml"
  - adminUser: {{ requiredEnv "GRAFANA_ADMIN_USER" }}
  - adminPassword: {{ requiredEnv "GRAFANA_ADMIN_PW" }}
  - serviceAccount:
      annotations:
        {{ requiredEnv "GRAFANA_SA_ANNOTATION" }}

- name: finops-dashboards
  version: "0.0.5"
  chart: "cert-manager/finops-dashboards"
  condition: finops-dashboards.enabled
  namespace: finops-stack
  needs:
  - grafana

- name: vpa
  version: "4.5.0"
  chart: "vpa/vpa"
  condition: vpa.enabled
  namespace: finops-stack
  values:
  - "./config/common/vpa-values.yaml"

- name: opencost
  version: "1.42.0"
  chart: "opencost/opencost"
  condition: opencost.enabled
  namespace: finops-stack
  values:
  - "./config/{{ requiredEnv "HOST_ENV" }}/opencost-values.yaml"
  - opencost:
      exporter:
        cloudProviderApiKey: {{ requiredEnv "CSP_API_KEY" }}

- name: prometheus-opencost-exporter
  version: "*"
  chart: "prometheus-opencost-exporter/prometheus-opencost-exporter"
  condition: opencost-exporter.enabled
  namespace: finops-stack
  needs:
  - opencost
  values:
  - "./config/common/prometheus-opencost-exporter-values.yaml"
  - "./config/{{ requiredEnv "HOST_ENV" }}/prometheus-opencost-exporter-values.yaml"
  - opencost:
      exporter:
        cloudProviderApiKey: {{ requiredEnv "CSP_API_KEY" }}

- name: finops-stack-opencost-templates
  version: "0.1.0"
  chart: "../chart/"
  condition: opencost-templates.enabled
  namespace: finops-stack
  disableValidationOnInstall: true
  needs:
  - opencost
  values:
  - "./config/{{ requiredEnv "HOST_ENV" }}/opencost-templates-values.yaml"