service:
  enabled: true
opencost:
  prometheus:
    external:
      enabled: false
      # url: http://prometheus-server
    internal:
      # -- Use in-cluster Prometheus
      enabled: true
      # -- Service name of in-cluster Prometheus
      serviceName: prometheus-server
      # -- Namespace of in-cluster Prometheus
      namespaceName: finops-stack
      # -- Service port of in-cluster Prometheus
      port: 80
  exporter:
    aws:
      # -- AWS secret access key
      secret_access_key: ""
      # -- AWS secret key id
      access_key_id: ""
    persistence:
      enabled: false
      # -- Annotations for persistent volume
      annotations: {}
      # -- Access mode for persistent volume
      accessMode: ""
      # -- Storage class for persistent volume
      storageClass: "standard-rwo"
      # -- Size for persistent volume
      size: "10g"
