apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: {{ include "gmp-proxy.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.selector: {{ include "gmp-proxy.fullname" . }}
    {{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
    {{- end }}
  name: {{ include "gmp-proxy.fullname" . }}
  namespace: {{ include "gmp-proxy.namespace" . }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 10000
  selector:
    app.selector: {{ include "gmp-proxy.fullname" . }}
  type: ClusterIP