name: Build Chart

on:
  workflow_dispatch: # Enable manual generation
  pull_request:
  push:
    branches:
      - "main"
    paths:
      - "chart/**"


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-chart
  cancel-in-progress: true

jobs:
  docs:
    name: Generate Helm Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Render helm docs inside the README.md
        # uses: shaybentk/helm-docs-action@v0.0.1
        uses: davidcollom/helm-docs-action@v0.0.2
        with:
          working-dir: chart/
          fail-on-diff: true

  lint:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests

    name: Lint Helm Chart
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chart/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: azure/setup-helm@v4

      - run: helm dep update
      - run: helm lint


  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chart/

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4

      - run: helm dep update

      # Ensure that the chart's default values produce manifests
      - run: helm template test .
