name: Build Chart

on:
  workflow_dispatch: # Enable manual generation
  pull_request:
  push:
    branches:
      - "main"
    paths:
      - "chart/**"


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-chart
  cancel-in-progress: true

jobs:
  docs:
    name: Generate Helm Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Render helm docs inside the README.md
        uses: shaybentk/helm-docs-action@v0.0.1
        with:
          working-dir: chart/
          fail-on-diff: true

  lint:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests

    name: Lint Helm Chart
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chart/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: azure/setup-helm@v4

      - run: helm dep update
      - run: helm lint


  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chart/

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4

      - run: helm dep update

      # Ensure that the chart's default values produce manifests
      - run: helm template test

      - if: ${{inputs.publish}}
        name: checkout jetstack-charts
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.JETSTACK_CHARTS_PAT }}
          repository: jetstack/jetstack-charts
          ref: main
          path: jetstack-charts

      - if: ${{inputs.publish}}
        name: Package helm chart
        working-directory: ./${{inputs.chart-name}}/chart/
        run: |
          helm package . -d jetstack-charts/charts/

      - name: Creating PR
        if: ${{inputs.publish}}
        uses: peter-evans/create-pull-request@v6.0.5
        with:
          token: ${{ secrets.JETSTACK_CHARTS_PAT }}
          title: "Release ${{inputs.chart-name}} ${{github.ref_name }}"
          commit-message: "Release ${{inputs.chart-name}} ${{github.ref_name }}"
          branch: ${{inputs.chart-name}}/${{github.ref_name}}
          path: jetstack-charts
          add-paths: charts/*.tgz
          delete-branch: true
          signoff: true
          base: main
          draft: false
