name: Publish Chart

on:
  workflow_dispatch: # Enable manual generation
  push:
    tags:
      - "v*"
    paths:
      - "chart/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-chart
  cancel-in-progress: true

jobs:
  lint:
    permissions:
      contents: read
      pull-requests: read

    name: Lint Helm Chart
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chart/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: azure/setup-helm@v4

      - run: helm dep update
      - run: helm lint

  github-release:
    needs:
      - build
      - lint
    name: Create/Update GitHub Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Release / Change Logs
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          generate_release_notes: true


  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chart/

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4

      - run: helm dep update

      # Ensure that the chart's default values produce manifests
      - run: helm template test ./

      - name: checkout jetstack-charts
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.JETSTACK_CHARTS_PAT }}
          repository: jetstack/jetstack-charts
          ref: main
          path: jetstack-charts

      - name: Package helm chart
        run: |
          helm package . -d ${{github.workspace}}/jetstack-charts/charts/

        # Only create the PR when we're triggered by a tag
      - if: contains(github.ref, 'refs/tags/')
        name: Creating PR
        uses: peter-evans/create-pull-request@v7.0.1
        with:
          token: ${{ secrets.JETSTACK_CHARTS_PAT }}
          title: "Release FinOps Stack ${{github.ref_name }}"
          commit-message: "Release FinOps Stack ${{github.ref_name }}"
          branch: finops-stack/${{github.ref_name}}
          path: jetstack-charts
          add-paths: charts/*.tgz
          delete-branch: true
          signoff: true
          base: main
          draft: false
